### ISSUE TITLE
Transaction details window not working in 2.11.0

### ISSUE THREAD

**Issue by mortomanos** [hsoft/moneyguru#488] opened 2017-08-26 06:10 UTC
I downloaded 2.11.0 today and installed it, since the auto upgrade feature from 2.10.2 did not work and always returned an error. After upgrading the transaction details window is working no more, even if I select only one transaction.
I also noticed that there is no more auto-upgrade menu entry in 2.11.0 - is this feature canceled?

**Comment by hsoft** [comment] 2017-08-26 19:58
Thanks for the warning. The problem is fixed in the newly released `2.11.0-1` mac version.

Yes, I've removed Sparkle (the auto-updater) because the old version was insecure and the new one didn't compile on Mac OS older than 10.10. For technical reasons I don't fully comprehend, I *have* to compile on the lowest Mac OS version I support (`MACOS_DEPLOYMENT_TARGET` isn't enough...).

Bumping requirements to 10.10 only for the updater felt like a bad idea, hence the removal. Maybe after 10.13 is released, I'll bump requirements to 10.10, and then re-introduce Sparkle (unless its own requirement bumps again until then...).

**Closed by hsoft** 2017-08-26 19:58 UTC
