### ISSUE TITLE
TypeError: QAction.setText(str): argument 1 has unexpected type 'int' in refresh_custom_ranges

### ISSUE THREAD

**Issue by rp42** [hsoft/moneyguru#468] opened 2016-11-17 21:10 UTC
Hello,

I set up a custom range to cover the next few years. After that moneyguru failed to start with this backtrace:
[backtrace.txt](https://github.com/hsoft/moneyguru/files/598472/backtrace.txt)

I edited moneyGuru.conf and deleted the CustomRanges line and it works again. Here is the line I deleted:
CustomRanges=@Variant(\0\0\0\t\0\0\0\x3\0\0\0\n\0\0\0\0\0\0\0\n\0\0\0\x14\0\x30\0\x36\0/\0\x30\0\x34\0/\0\x32\0\x30\0\x31\0\x34\0\0\\
0\n\0\0\0\x14\0\x30\0\x35\0/\0\x30\0\x34\0/\0\x32\0\x30\0\x31\0\x35), @Variant(\0\0\0\t\0\0\0\x3\0\0\0\n\0\0\0\b\0\x32\0\x30\0\x32\0\
\x30\0\0\0\n\0\0\0\x14\0\x30\0\x36\0/\0\x30\0\x34\0/\0\x32\0\x30\0\x31\0\x36\0\0\0\n\0\0\0\x14\0\x30\0\x35\0/\0\x30\0\x34\0/\0\x32\0\
\x30\0\x32\0\x30), @Variant(\0\0\0\t\0\0\0\0)

**Comment by aeroaks** [comment] 2017-03-05 15:08
@hsoft  I do not know the ful thing, but can the solution to explicitly convert the input to string be acceptable? (something like this: `action.setText(str(name))`)

**Comment by hsoft** [comment] 2017-03-08 22:58
@aeroaks nobody knows the full thing because it's a bug that has yet to be reliably reproduced. One hint I can give you, however, is that it's not normal that `@Variant` value type end up in the preferences, so that's probably the root cause of our problem.

So, the challenge here is to find under which conditions we end up with corrupted values in our config file and fix it.

**Comment by hsoft** [comment] 2019-01-03 01:41
What was I saying earlier again? There are many variables, including `CustomRanges`, that end up being saved as `@Variant`. All the time. That should be fixed.

**Closed** 2019-01-03 13:46 UTC
Labels: bug
